/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import raubach.sgud.server.database.tables.Categories;
import raubach.sgud.server.database.tables.Images;
import raubach.sgud.server.database.tables.ItemImages;
import raubach.sgud.server.database.tables.ItemRatings;
import raubach.sgud.server.database.tables.Items;
import raubach.sgud.server.database.tables.Manufacturers;
import raubach.sgud.server.database.tables.RatingCategories;
import raubach.sgud.server.database.tables.SchemaVersion;
import raubach.sgud.server.database.tables.Sources;
import raubach.sgud.server.database.tables.Types;


/**
 * A class modelling indexes of tables of the <code>sgud</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORIES_NAME = Indexes0.CATEGORIES_NAME;
    public static final Index CATEGORIES_PRIMARY = Indexes0.CATEGORIES_PRIMARY;
    public static final Index IMAGES_PRIMARY = Indexes0.IMAGES_PRIMARY;
    public static final Index ITEM_IMAGES_ITEMIMAGES_IBFK_IMAGES = Indexes0.ITEM_IMAGES_ITEMIMAGES_IBFK_IMAGES;
    public static final Index ITEM_IMAGES_PRIMARY = Indexes0.ITEM_IMAGES_PRIMARY;
    public static final Index ITEM_RATINGS_ITEM_RATINGS_IBFK_RATINGCATEGORY = Indexes0.ITEM_RATINGS_ITEM_RATINGS_IBFK_RATINGCATEGORY;
    public static final Index ITEM_RATINGS_PRIMARY = Indexes0.ITEM_RATINGS_PRIMARY;
    public static final Index ITEMS_ITEMS_IBFK_CATEGORIES = Indexes0.ITEMS_ITEMS_IBFK_CATEGORIES;
    public static final Index ITEMS_ITEMS_IBFK_MANUFACTURER = Indexes0.ITEMS_ITEMS_IBFK_MANUFACTURER;
    public static final Index ITEMS_ITEMS_IBFK_SOURCE = Indexes0.ITEMS_ITEMS_IBFK_SOURCE;
    public static final Index ITEMS_ITEMS_IBFK_TYPE = Indexes0.ITEMS_ITEMS_IBFK_TYPE;
    public static final Index ITEMS_NAME = Indexes0.ITEMS_NAME;
    public static final Index ITEMS_PRIMARY = Indexes0.ITEMS_PRIMARY;
    public static final Index MANUFACTURERS_PRIMARY = Indexes0.MANUFACTURERS_PRIMARY;
    public static final Index RATING_CATEGORIES_PRIMARY = Indexes0.RATING_CATEGORIES_PRIMARY;
    public static final Index RATING_CATEGORIES_RATINGCATEGORIES_IBFK_CATEGORY = Indexes0.RATING_CATEGORIES_RATINGCATEGORIES_IBFK_CATEGORY;
    public static final Index SCHEMA_VERSION_PRIMARY = Indexes0.SCHEMA_VERSION_PRIMARY;
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Indexes0.SCHEMA_VERSION_SCHEMA_VERSION_S_IDX;
    public static final Index SOURCES_NAME = Indexes0.SOURCES_NAME;
    public static final Index SOURCES_PRIMARY = Indexes0.SOURCES_PRIMARY;
    public static final Index TYPES_NAME = Indexes0.TYPES_NAME;
    public static final Index TYPES_PRIMARY = Indexes0.TYPES_PRIMARY;
    public static final Index TYPES_TYPE_IBFK_CATEGORY = Indexes0.TYPES_TYPE_IBFK_CATEGORY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORIES_NAME = Internal.createIndex("name", Categories.CATEGORIES, new OrderField[] { Categories.CATEGORIES.NAME }, false);
        public static Index CATEGORIES_PRIMARY = Internal.createIndex("PRIMARY", Categories.CATEGORIES, new OrderField[] { Categories.CATEGORIES.ID }, true);
        public static Index IMAGES_PRIMARY = Internal.createIndex("PRIMARY", Images.IMAGES, new OrderField[] { Images.IMAGES.ID }, true);
        public static Index ITEM_IMAGES_ITEMIMAGES_IBFK_IMAGES = Internal.createIndex("itemimages_ibfk_images", ItemImages.ITEM_IMAGES, new OrderField[] { ItemImages.ITEM_IMAGES.IMAGE_ID }, false);
        public static Index ITEM_IMAGES_PRIMARY = Internal.createIndex("PRIMARY", ItemImages.ITEM_IMAGES, new OrderField[] { ItemImages.ITEM_IMAGES.ITEM_ID, ItemImages.ITEM_IMAGES.IMAGE_ID }, true);
        public static Index ITEM_RATINGS_ITEM_RATINGS_IBFK_RATINGCATEGORY = Internal.createIndex("item_ratings_ibfk_ratingcategory", ItemRatings.ITEM_RATINGS, new OrderField[] { ItemRatings.ITEM_RATINGS.RATINGCATEGORY_ID }, false);
        public static Index ITEM_RATINGS_PRIMARY = Internal.createIndex("PRIMARY", ItemRatings.ITEM_RATINGS, new OrderField[] { ItemRatings.ITEM_RATINGS.ITEM_ID, ItemRatings.ITEM_RATINGS.RATINGCATEGORY_ID }, true);
        public static Index ITEMS_ITEMS_IBFK_CATEGORIES = Internal.createIndex("items_ibfk_categories", Items.ITEMS, new OrderField[] { Items.ITEMS.CATEGORY_ID }, false);
        public static Index ITEMS_ITEMS_IBFK_MANUFACTURER = Internal.createIndex("items_ibfk_manufacturer", Items.ITEMS, new OrderField[] { Items.ITEMS.MANUFACTURER_ID }, false);
        public static Index ITEMS_ITEMS_IBFK_SOURCE = Internal.createIndex("items_ibfk_source", Items.ITEMS, new OrderField[] { Items.ITEMS.SOURCE_ID }, false);
        public static Index ITEMS_ITEMS_IBFK_TYPE = Internal.createIndex("items_ibfk_type", Items.ITEMS, new OrderField[] { Items.ITEMS.TYPE_ID }, false);
        public static Index ITEMS_NAME = Internal.createIndex("name", Items.ITEMS, new OrderField[] { Items.ITEMS.NAME }, false);
        public static Index ITEMS_PRIMARY = Internal.createIndex("PRIMARY", Items.ITEMS, new OrderField[] { Items.ITEMS.ID }, true);
        public static Index MANUFACTURERS_PRIMARY = Internal.createIndex("PRIMARY", Manufacturers.MANUFACTURERS, new OrderField[] { Manufacturers.MANUFACTURERS.ID }, true);
        public static Index RATING_CATEGORIES_PRIMARY = Internal.createIndex("PRIMARY", RatingCategories.RATING_CATEGORIES, new OrderField[] { RatingCategories.RATING_CATEGORIES.ID }, true);
        public static Index RATING_CATEGORIES_RATINGCATEGORIES_IBFK_CATEGORY = Internal.createIndex("ratingcategories_ibfk_category", RatingCategories.RATING_CATEGORIES, new OrderField[] { RatingCategories.RATING_CATEGORIES.CATEGORY_ID }, false);
        public static Index SCHEMA_VERSION_PRIMARY = Internal.createIndex("PRIMARY", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, true);
        public static Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Internal.createIndex("schema_version_s_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
        public static Index SOURCES_NAME = Internal.createIndex("name", Sources.SOURCES, new OrderField[] { Sources.SOURCES.NAME }, false);
        public static Index SOURCES_PRIMARY = Internal.createIndex("PRIMARY", Sources.SOURCES, new OrderField[] { Sources.SOURCES.ID }, true);
        public static Index TYPES_NAME = Internal.createIndex("name", Types.TYPES, new OrderField[] { Types.TYPES.NAME }, false);
        public static Index TYPES_PRIMARY = Internal.createIndex("PRIMARY", Types.TYPES, new OrderField[] { Types.TYPES.ID }, true);
        public static Index TYPES_TYPE_IBFK_CATEGORY = Internal.createIndex("type_ibfk_category", Types.TYPES, new OrderField[] { Types.TYPES.CATEGORY_ID }, false);
    }
}
