/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sgud extends SchemaImpl {

    private static final long serialVersionUID = -828206580;

    /**
     * The reference instance of <code>sgud</code>
     */
    public static final Sgud SGUD = new Sgud();

    /**
     * No further instances allowed
     */
    private Sgud() {
        super("sgud", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
