/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryImages implements Serializable {

    private static final long serialVersionUID = 747714813;

    private Integer categoryId;
    private Integer imageId;

    public CategoryImages() {}

    public CategoryImages(CategoryImages value) {
        this.categoryId = value.categoryId;
        this.imageId = value.imageId;
    }

    public CategoryImages(
        Integer categoryId,
        Integer imageId
    ) {
        this.categoryId = categoryId;
        this.imageId = imageId;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryImages (");

        sb.append(categoryId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
