/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemImages implements Serializable {

    private static final long serialVersionUID = 30191164;

    private Integer itemId;
    private Integer imageId;

    public ItemImages() {}

    public ItemImages(ItemImages value) {
        this.itemId = value.itemId;
        this.imageId = value.imageId;
    }

    public ItemImages(
        Integer itemId,
        Integer imageId
    ) {
        this.itemId = itemId;
        this.imageId = imageId;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemImages (");

        sb.append(itemId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
