/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRatings implements Serializable {

    private static final long serialVersionUID = 1044725516;

    private Integer   itemId;
    private Integer   ratingcategoryId;
    private Double    rating;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ItemRatings() {}

    public ItemRatings(ItemRatings value) {
        this.itemId = value.itemId;
        this.ratingcategoryId = value.ratingcategoryId;
        this.rating = value.rating;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ItemRatings(
        Integer   itemId,
        Integer   ratingcategoryId,
        Double    rating,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.itemId = itemId;
        this.ratingcategoryId = ratingcategoryId;
        this.rating = rating;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getRatingcategoryId() {
        return this.ratingcategoryId;
    }

    public void setRatingcategoryId(Integer ratingcategoryId) {
        this.ratingcategoryId = ratingcategoryId;
    }

    public Double getRating() {
        return this.rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemRatings (");

        sb.append(itemId);
        sb.append(", ").append(ratingcategoryId);
        sb.append(", ").append(rating);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
