/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManufacturerImages implements Serializable {

    private static final long serialVersionUID = 1195264374;

    private Integer manufacturerId;
    private Integer imageId;

    public ManufacturerImages() {}

    public ManufacturerImages(ManufacturerImages value) {
        this.manufacturerId = value.manufacturerId;
        this.imageId = value.imageId;
    }

    public ManufacturerImages(
        Integer manufacturerId,
        Integer imageId
    ) {
        this.manufacturerId = manufacturerId;
        this.imageId = imageId;
    }

    public Integer getManufacturerId() {
        return this.manufacturerId;
    }

    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ManufacturerImages (");

        sb.append(manufacturerId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
