/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingCategories implements Serializable {

    private static final long serialVersionUID = 1922772520;

    private Integer   id;
    private Integer   categoryId;
    private String    name;
    private String    description;
    private Boolean   includeInAverage;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public RatingCategories() {}

    public RatingCategories(RatingCategories value) {
        this.id = value.id;
        this.categoryId = value.categoryId;
        this.name = value.name;
        this.description = value.description;
        this.includeInAverage = value.includeInAverage;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public RatingCategories(
        Integer   id,
        Integer   categoryId,
        String    name,
        String    description,
        Boolean   includeInAverage,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.categoryId = categoryId;
        this.name = name;
        this.description = description;
        this.includeInAverage = includeInAverage;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIncludeInAverage() {
        return this.includeInAverage;
    }

    public void setIncludeInAverage(Boolean includeInAverage) {
        this.includeInAverage = includeInAverage;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RatingCategories (");

        sb.append(id);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(includeInAverage);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
