/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeImages implements Serializable {

    private static final long serialVersionUID = -1378711759;

    private Integer typeId;
    private Integer imageId;

    public TypeImages() {}

    public TypeImages(TypeImages value) {
        this.typeId = value.typeId;
        this.imageId = value.imageId;
    }

    public TypeImages(
        Integer typeId,
        Integer imageId
    ) {
        this.typeId = typeId;
        this.imageId = imageId;
    }

    public Integer getTypeId() {
        return this.typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TypeImages (");

        sb.append(typeId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
