/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCategories implements Serializable {

    private static final long serialVersionUID = 358740901;

    private Integer   id;
    private String    name;
    private String    description;
    private String    icon;
    private Timestamp createdOn;
    private Timestamp updatedOn;
    private Long      count;

    public ViewCategories() {}

    public ViewCategories(ViewCategories value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.icon = value.icon;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.count = value.count;
    }

    public ViewCategories(
        Integer   id,
        String    name,
        String    description,
        String    icon,
        Timestamp createdOn,
        Timestamp updatedOn,
        Long      count
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.icon = icon;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.count = count;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Long getCount() {
        return this.count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewCategories (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(icon);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
