/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewRatings implements Serializable {

    private static final long serialVersionUID = 627153017;

    private Integer itemId;
    private String  itemName;
    private String  itemDescription;
    private Integer ratingCategoryId;
    private String  ratingCategoryName;
    private String  ratingCategoryDescription;
    private Integer categoryId;
    private String  categoryName;
    private String  categoryDescription;
    private Double  rating;

    public ViewRatings() {}

    public ViewRatings(ViewRatings value) {
        this.itemId = value.itemId;
        this.itemName = value.itemName;
        this.itemDescription = value.itemDescription;
        this.ratingCategoryId = value.ratingCategoryId;
        this.ratingCategoryName = value.ratingCategoryName;
        this.ratingCategoryDescription = value.ratingCategoryDescription;
        this.categoryId = value.categoryId;
        this.categoryName = value.categoryName;
        this.categoryDescription = value.categoryDescription;
        this.rating = value.rating;
    }

    public ViewRatings(
        Integer itemId,
        String  itemName,
        String  itemDescription,
        Integer ratingCategoryId,
        String  ratingCategoryName,
        String  ratingCategoryDescription,
        Integer categoryId,
        String  categoryName,
        String  categoryDescription,
        Double  rating
    ) {
        this.itemId = itemId;
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.ratingCategoryId = ratingCategoryId;
        this.ratingCategoryName = ratingCategoryName;
        this.ratingCategoryDescription = ratingCategoryDescription;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.categoryDescription = categoryDescription;
        this.rating = rating;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public Integer getRatingCategoryId() {
        return this.ratingCategoryId;
    }

    public void setRatingCategoryId(Integer ratingCategoryId) {
        this.ratingCategoryId = ratingCategoryId;
    }

    public String getRatingCategoryName() {
        return this.ratingCategoryName;
    }

    public void setRatingCategoryName(String ratingCategoryName) {
        this.ratingCategoryName = ratingCategoryName;
    }

    public String getRatingCategoryDescription() {
        return this.ratingCategoryDescription;
    }

    public void setRatingCategoryDescription(String ratingCategoryDescription) {
        this.ratingCategoryDescription = ratingCategoryDescription;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryDescription() {
        return this.categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public Double getRating() {
        return this.rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewRatings (");

        sb.append(itemId);
        sb.append(", ").append(itemName);
        sb.append(", ").append(itemDescription);
        sb.append(", ").append(ratingCategoryId);
        sb.append(", ").append(ratingCategoryName);
        sb.append(", ").append(ratingCategoryDescription);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(categoryDescription);
        sb.append(", ").append(rating);

        sb.append(")");
        return sb.toString();
    }
}
