/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCategoryStats implements Serializable {

    private static final long serialVersionUID = 253012838;

    private Integer categoryId;
    private String  month;
    private Long    count;

    public ViewCategoryStats() {}

    public ViewCategoryStats(ViewCategoryStats value) {
        this.categoryId = value.categoryId;
        this.month = value.month;
        this.count = value.count;
    }

    public ViewCategoryStats(
        Integer categoryId,
        String  month,
        Long    count
    ) {
        this.categoryId = categoryId;
        this.month = month;
        this.count = count;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Long getCount() {
        return this.count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewCategoryStats (");

        sb.append(categoryId);
        sb.append(", ").append(month);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
