/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import raubach.sgud.server.database.Indexes;
import raubach.sgud.server.database.Sgud;
import raubach.sgud.server.database.tables.records.SourcesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sources extends TableImpl<SourcesRecord> {

    private static final long serialVersionUID = -26239068;

    /**
     * The reference instance of <code>sgud.sources</code>
     */
    public static final Sources SOURCES = new Sources();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourcesRecord> getRecordType() {
        return SourcesRecord.class;
    }

    /**
     * The column <code>sgud.sources.id</code>.
     */
    public final TableField<SourcesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sgud.sources.name</code>.
     */
    public final TableField<SourcesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sgud.sources.description</code>.
     */
    public final TableField<SourcesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.sources.url</code>.
     */
    public final TableField<SourcesRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.sources.created_on</code>.
     */
    public final TableField<SourcesRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>sgud.sources.updated_on</code>.
     */
    public final TableField<SourcesRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>sgud.sources</code> table reference
     */
    public Sources() {
        this(DSL.name("sources"), null);
    }

    /**
     * Create an aliased <code>sgud.sources</code> table reference
     */
    public Sources(String alias) {
        this(DSL.name(alias), SOURCES);
    }

    /**
     * Create an aliased <code>sgud.sources</code> table reference
     */
    public Sources(Name alias) {
        this(alias, SOURCES);
    }

    private Sources(Name alias, Table<SourcesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sources(Name alias, Table<SourcesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sgud.SGUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SOURCES_NAME, Indexes.SOURCES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SourcesRecord, Integer> getIdentity() {
        return Internal.createIdentity(raubach.sgud.server.database.tables.Sources.SOURCES, raubach.sgud.server.database.tables.Sources.SOURCES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SourcesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(raubach.sgud.server.database.tables.Sources.SOURCES, "KEY_sources_PRIMARY", raubach.sgud.server.database.tables.Sources.SOURCES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SourcesRecord>> getKeys() {
        return Arrays.<UniqueKey<SourcesRecord>>asList(
              Internal.createUniqueKey(raubach.sgud.server.database.tables.Sources.SOURCES, "KEY_sources_PRIMARY", raubach.sgud.server.database.tables.Sources.SOURCES.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sources as(String alias) {
        return new Sources(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sources as(Name alias) {
        return new Sources(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sources rename(String name) {
        return new Sources(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sources rename(Name name) {
        return new Sources(name, null);
    }
}
