/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import raubach.sgud.server.database.Indexes;
import raubach.sgud.server.database.Sgud;
import raubach.sgud.server.database.tables.records.TypeImagesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeImages extends TableImpl<TypeImagesRecord> {

    private static final long serialVersionUID = 1779290791;

    /**
     * The reference instance of <code>sgud.type_images</code>
     */
    public static final TypeImages TYPE_IMAGES = new TypeImages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeImagesRecord> getRecordType() {
        return TypeImagesRecord.class;
    }

    /**
     * The column <code>sgud.type_images.type_id</code>.
     */
    public final TableField<TypeImagesRecord, Integer> TYPE_ID = createField("type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sgud.type_images.image_id</code>.
     */
    public final TableField<TypeImagesRecord, Integer> IMAGE_ID = createField("image_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sgud.type_images</code> table reference
     */
    public TypeImages() {
        this(DSL.name("type_images"), null);
    }

    /**
     * Create an aliased <code>sgud.type_images</code> table reference
     */
    public TypeImages(String alias) {
        this(DSL.name(alias), TYPE_IMAGES);
    }

    /**
     * Create an aliased <code>sgud.type_images</code> table reference
     */
    public TypeImages(Name alias) {
        this(alias, TYPE_IMAGES);
    }

    private TypeImages(Name alias, Table<TypeImagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TypeImages(Name alias, Table<TypeImagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sgud.SGUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_IMAGES_PRIMARY, Indexes.TYPE_IMAGES_TYPEIMAGES_IBFK_IMAGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypeImagesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES, "KEY_type_images_PRIMARY", raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES.TYPE_ID, raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES.IMAGE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypeImagesRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeImagesRecord>>asList(
              Internal.createUniqueKey(raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES, "KEY_type_images_PRIMARY", raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES.TYPE_ID, raubach.sgud.server.database.tables.TypeImages.TYPE_IMAGES.IMAGE_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeImages as(String alias) {
        return new TypeImages(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeImages as(Name alias) {
        return new TypeImages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeImages rename(String name) {
        return new TypeImages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeImages rename(Name name) {
        return new TypeImages(name, null);
    }
}
