/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables;


import com.google.gson.JsonArray;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import raubach.sgud.server.binding.JsonStringArrayBinding;
import raubach.sgud.server.database.Sgud;
import raubach.sgud.server.database.tables.records.ViewRatingsRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewRatings extends TableImpl<ViewRatingsRecord> {

    private static final long serialVersionUID = -558673563;

    /**
     * The reference instance of <code>sgud.view_ratings</code>
     */
    public static final ViewRatings VIEW_RATINGS = new ViewRatings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewRatingsRecord> getRecordType() {
        return ViewRatingsRecord.class;
    }

    /**
     * The column <code>sgud.view_ratings.item_id</code>.
     */
    public final TableField<ViewRatingsRecord, Integer> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_ratings.item_name</code>.
     */
    public final TableField<ViewRatingsRecord, String> ITEM_NAME = createField("item_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_ratings.item_description</code>.
     */
    public final TableField<ViewRatingsRecord, String> ITEM_DESCRIPTION = createField("item_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_ratings.item_tags</code>.
     */
    public final TableField<ViewRatingsRecord, JsonArray> ITEM_TAGS = createField("item_tags", org.jooq.impl.DefaultDataType.getDefaultDataType("\"sgud\".\"view_ratings_item_tags\""), this, "", new JsonStringArrayBinding());

    /**
     * The column <code>sgud.view_ratings.rating_category_id</code>.
     */
    public final TableField<ViewRatingsRecord, Integer> RATING_CATEGORY_ID = createField("rating_category_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_ratings.rating_category_name</code>.
     */
    public final TableField<ViewRatingsRecord, String> RATING_CATEGORY_NAME = createField("rating_category_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_ratings.rating_category_description</code>.
     */
    public final TableField<ViewRatingsRecord, String> RATING_CATEGORY_DESCRIPTION = createField("rating_category_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_ratings.category_id</code>.
     */
    public final TableField<ViewRatingsRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_ratings.category_name</code>.
     */
    public final TableField<ViewRatingsRecord, String> CATEGORY_NAME = createField("category_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_ratings.category_description</code>.
     */
    public final TableField<ViewRatingsRecord, String> CATEGORY_DESCRIPTION = createField("category_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_ratings.rating</code>.
     */
    public final TableField<ViewRatingsRecord, Double> RATING = createField("rating", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * Create a <code>sgud.view_ratings</code> table reference
     */
    public ViewRatings() {
        this(DSL.name("view_ratings"), null);
    }

    /**
     * Create an aliased <code>sgud.view_ratings</code> table reference
     */
    public ViewRatings(String alias) {
        this(DSL.name(alias), VIEW_RATINGS);
    }

    /**
     * Create an aliased <code>sgud.view_ratings</code> table reference
     */
    public ViewRatings(Name alias) {
        this(alias, VIEW_RATINGS);
    }

    private ViewRatings(Name alias, Table<ViewRatingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewRatings(Name alias, Table<ViewRatingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sgud.SGUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatings as(String alias) {
        return new ViewRatings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatings as(Name alias) {
        return new ViewRatings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewRatings rename(String name) {
        return new ViewRatings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewRatings rename(Name name) {
        return new ViewRatings(name, null);
    }
}
