/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import raubach.sgud.server.database.Sgud;
import raubach.sgud.server.database.tables.records.ViewCategoryStatsRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCategoryStats extends TableImpl<ViewCategoryStatsRecord> {

    private static final long serialVersionUID = 272668946;

    /**
     * The reference instance of <code>sgud.view_category_stats</code>
     */
    public static final ViewCategoryStats VIEW_CATEGORY_STATS = new ViewCategoryStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewCategoryStatsRecord> getRecordType() {
        return ViewCategoryStatsRecord.class;
    }

    /**
     * The column <code>sgud.view_category_stats.category_id</code>.
     */
    public final TableField<ViewCategoryStatsRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_category_stats.month</code>.
     */
    public final TableField<ViewCategoryStatsRecord, String> MONTH = createField("month", org.jooq.impl.SQLDataType.VARCHAR(7), this, "");

    /**
     * The column <code>sgud.view_category_stats.count</code>.
     */
    public final TableField<ViewCategoryStatsRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>sgud.view_category_stats.max</code>.
     */
    public final TableField<ViewCategoryStatsRecord, Long> MAX = createField("max", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>sgud.view_category_stats</code> table reference
     */
    public ViewCategoryStats() {
        this(DSL.name("view_category_stats"), null);
    }

    /**
     * Create an aliased <code>sgud.view_category_stats</code> table reference
     */
    public ViewCategoryStats(String alias) {
        this(DSL.name(alias), VIEW_CATEGORY_STATS);
    }

    /**
     * Create an aliased <code>sgud.view_category_stats</code> table reference
     */
    public ViewCategoryStats(Name alias) {
        this(alias, VIEW_CATEGORY_STATS);
    }

    private ViewCategoryStats(Name alias, Table<ViewCategoryStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewCategoryStats(Name alias, Table<ViewCategoryStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sgud.SGUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStats as(String alias) {
        return new ViewCategoryStats(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStats as(Name alias) {
        return new ViewCategoryStats(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewCategoryStats rename(String name) {
        return new ViewCategoryStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewCategoryStats rename(Name name) {
        return new ViewCategoryStats(name, null);
    }
}
