/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import raubach.sgud.server.database.Sgud;
import raubach.sgud.server.database.tables.records.ViewItemsRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewItems extends TableImpl<ViewItemsRecord> {

    private static final long serialVersionUID = 680141522;

    /**
     * The reference instance of <code>sgud.view_items</code>
     */
    public static final ViewItems VIEW_ITEMS = new ViewItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewItemsRecord> getRecordType() {
        return ViewItemsRecord.class;
    }

    /**
     * The column <code>sgud.view_items.item_id</code>.
     */
    public final TableField<ViewItemsRecord, Integer> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_items.item_name</code>.
     */
    public final TableField<ViewItemsRecord, String> ITEM_NAME = createField("item_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sgud.view_items.item_description</code>.
     */
    public final TableField<ViewItemsRecord, String> ITEM_DESCRIPTION = createField("item_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.item_created_on</code>.
     */
    public final TableField<ViewItemsRecord, Timestamp> ITEM_CREATED_ON = createField("item_created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>sgud.view_items.manufacturer_id</code>.
     */
    public final TableField<ViewItemsRecord, Integer> MANUFACTURER_ID = createField("manufacturer_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_items.manufacturer_name</code>.
     */
    public final TableField<ViewItemsRecord, String> MANUFACTURER_NAME = createField("manufacturer_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_items.manufacturer_description</code>.
     */
    public final TableField<ViewItemsRecord, String> MANUFACTURER_DESCRIPTION = createField("manufacturer_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.manufacturer_url</code>.
     */
    public final TableField<ViewItemsRecord, String> MANUFACTURER_URL = createField("manufacturer_url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.source_id</code>.
     */
    public final TableField<ViewItemsRecord, Integer> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_items.source_name</code>.
     */
    public final TableField<ViewItemsRecord, String> SOURCE_NAME = createField("source_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_items.source_description</code>.
     */
    public final TableField<ViewItemsRecord, String> SOURCE_DESCRIPTION = createField("source_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.source_url</code>.
     */
    public final TableField<ViewItemsRecord, String> SOURCE_URL = createField("source_url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.category_id</code>.
     */
    public final TableField<ViewItemsRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_items.category_name</code>.
     */
    public final TableField<ViewItemsRecord, String> CATEGORY_NAME = createField("category_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_items.category_description</code>.
     */
    public final TableField<ViewItemsRecord, String> CATEGORY_DESCRIPTION = createField("category_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.category_icon</code>.
     */
    public final TableField<ViewItemsRecord, String> CATEGORY_ICON = createField("category_icon", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>sgud.view_items.type_id</code>.
     */
    public final TableField<ViewItemsRecord, Integer> TYPE_ID = createField("type_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sgud.view_items.type_name</code>.
     */
    public final TableField<ViewItemsRecord, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sgud.view_items.type_description</code>.
     */
    public final TableField<ViewItemsRecord, String> TYPE_DESCRIPTION = createField("type_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sgud.view_items.type_icon</code>.
     */
    public final TableField<ViewItemsRecord, String> TYPE_ICON = createField("type_icon", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>sgud.view_items.avg_item_rating</code>.
     */
    public final TableField<ViewItemsRecord, Double> AVG_ITEM_RATING = createField("avg_item_rating", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>sgud.view_items</code> table reference
     */
    public ViewItems() {
        this(DSL.name("view_items"), null);
    }

    /**
     * Create an aliased <code>sgud.view_items</code> table reference
     */
    public ViewItems(String alias) {
        this(DSL.name(alias), VIEW_ITEMS);
    }

    /**
     * Create an aliased <code>sgud.view_items</code> table reference
     */
    public ViewItems(Name alias) {
        this(alias, VIEW_ITEMS);
    }

    private ViewItems(Name alias, Table<ViewItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewItems(Name alias, Table<ViewItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sgud.SGUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewItems as(String alias) {
        return new ViewItems(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewItems as(Name alias) {
        return new ViewItems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewItems rename(String name) {
        return new ViewItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewItems rename(Name name) {
        return new ViewItems(name, null);
    }
}
