/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import raubach.sgud.server.database.tables.ManufacturerImages;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManufacturerImagesRecord extends UpdatableRecordImpl<ManufacturerImagesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -331092796;

    /**
     * Setter for <code>sgud.manufacturer_images.manufacturer_id</code>.
     */
    public void setManufacturerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sgud.manufacturer_images.manufacturer_id</code>.
     */
    public Integer getManufacturerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sgud.manufacturer_images.image_id</code>.
     */
    public void setImageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sgud.manufacturer_images.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ManufacturerImages.MANUFACTURER_IMAGES.MANUFACTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ManufacturerImages.MANUFACTURER_IMAGES.IMAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerImagesRecord value1(Integer value) {
        setManufacturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerImagesRecord value2(Integer value) {
        setImageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerImagesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManufacturerImagesRecord
     */
    public ManufacturerImagesRecord() {
        super(ManufacturerImages.MANUFACTURER_IMAGES);
    }

    /**
     * Create a detached, initialised ManufacturerImagesRecord
     */
    public ManufacturerImagesRecord(Integer manufacturerId, Integer imageId) {
        super(ManufacturerImages.MANUFACTURER_IMAGES);

        set(0, manufacturerId);
        set(1, imageId);
    }
}
