/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import raubach.sgud.server.database.tables.ViewCategoryStats;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCategoryStatsRecord extends TableRecordImpl<ViewCategoryStatsRecord> implements Record4<Integer, String, Long, Long> {

    private static final long serialVersionUID = 1572578037;

    /**
     * Setter for <code>sgud.view_category_stats.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sgud.view_category_stats.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sgud.view_category_stats.month</code>.
     */
    public void setMonth(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sgud.view_category_stats.month</code>.
     */
    public String getMonth() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sgud.view_category_stats.count</code>.
     */
    public void setCount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>sgud.view_category_stats.count</code>.
     */
    public Long getCount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>sgud.view_category_stats.max</code>.
     */
    public void setMax(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>sgud.view_category_stats.max</code>.
     */
    public Long getMax() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewCategoryStats.VIEW_CATEGORY_STATS.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewCategoryStats.VIEW_CATEGORY_STATS.MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ViewCategoryStats.VIEW_CATEGORY_STATS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ViewCategoryStats.VIEW_CATEGORY_STATS.MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStatsRecord value1(Integer value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStatsRecord value2(String value) {
        setMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStatsRecord value3(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStatsRecord value4(Long value) {
        setMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewCategoryStatsRecord values(Integer value1, String value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewCategoryStatsRecord
     */
    public ViewCategoryStatsRecord() {
        super(ViewCategoryStats.VIEW_CATEGORY_STATS);
    }

    /**
     * Create a detached, initialised ViewCategoryStatsRecord
     */
    public ViewCategoryStatsRecord(Integer categoryId, String month, Long count, Long max) {
        super(ViewCategoryStats.VIEW_CATEGORY_STATS);

        set(0, categoryId);
        set(1, month);
        set(2, count);
        set(3, max);
    }
}
