/*
 * This file is generated by jOOQ.
 */
package raubach.sgud.server.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;

import raubach.sgud.server.database.tables.ViewRatings;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewRatingsRecord extends TableRecordImpl<ViewRatingsRecord> implements Record9<Integer, String, String, Integer, String, String, String, String, Double> {

    private static final long serialVersionUID = -533400686;

    /**
     * Setter for <code>sgud.view_ratings.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sgud.view_ratings.item_name</code>.
     */
    public void setItemName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.item_name</code>.
     */
    public String getItemName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sgud.view_ratings.item_description</code>.
     */
    public void setItemDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.item_description</code>.
     */
    public String getItemDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sgud.view_ratings.rating_category_id</code>.
     */
    public void setRatingCategoryId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.rating_category_id</code>.
     */
    public Integer getRatingCategoryId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sgud.view_ratings.rating_category_name</code>.
     */
    public void setRatingCategoryName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.rating_category_name</code>.
     */
    public String getRatingCategoryName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sgud.view_ratings.rating_category_description</code>.
     */
    public void setRatingCategoryDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.rating_category_description</code>.
     */
    public String getRatingCategoryDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sgud.view_ratings.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sgud.view_ratings.category_description</code>.
     */
    public void setCategoryDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.category_description</code>.
     */
    public String getCategoryDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sgud.view_ratings.rating</code>.
     */
    public void setRating(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>sgud.view_ratings.rating</code>.
     */
    public Double getRating() {
        return (Double) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Integer, String, String, String, String, Double> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Integer, String, String, String, String, Double> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewRatings.VIEW_RATINGS.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewRatings.VIEW_RATINGS.ITEM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewRatings.VIEW_RATINGS.ITEM_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewRatings.VIEW_RATINGS.RATING_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewRatings.VIEW_RATINGS.RATING_CATEGORY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewRatings.VIEW_RATINGS.RATING_CATEGORY_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewRatings.VIEW_RATINGS.CATEGORY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ViewRatings.VIEW_RATINGS.CATEGORY_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return ViewRatings.VIEW_RATINGS.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getItemName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getItemDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRatingCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRatingCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRatingCategoryDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCategoryDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getItemName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getItemDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRatingCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRatingCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRatingCategoryDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCategoryDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value1(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value2(String value) {
        setItemName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value3(String value) {
        setItemDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value4(Integer value) {
        setRatingCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value5(String value) {
        setRatingCategoryName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value6(String value) {
        setRatingCategoryDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value7(String value) {
        setCategoryName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value8(String value) {
        setCategoryDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord value9(Double value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewRatingsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, Double value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewRatingsRecord
     */
    public ViewRatingsRecord() {
        super(ViewRatings.VIEW_RATINGS);
    }

    /**
     * Create a detached, initialised ViewRatingsRecord
     */
    public ViewRatingsRecord(Integer itemId, String itemName, String itemDescription, Integer ratingCategoryId, String ratingCategoryName, String ratingCategoryDescription, String categoryName, String categoryDescription, Double rating) {
        super(ViewRatings.VIEW_RATINGS);

        set(0, itemId);
        set(1, itemName);
        set(2, itemDescription);
        set(3, ratingCategoryId);
        set(4, ratingCategoryName);
        set(5, ratingCategoryDescription);
        set(6, categoryName);
        set(7, categoryDescription);
        set(8, rating);
    }
}
